version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    container_name: tecnoguard-app-dev
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:h2:mem:tecnoguard_test;DB_CLOSE_DELAY=1;DB_CLOSE_ON_EXIT=FALSE
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD:
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
    ports:
      - "${SERVER_PORT:-8080}:8080"
    volumes:
      - ./logs:/app/logs
      - ./src:/app/src
      - ~/.m2:/root/.m2
    networks:
      - tecnoguard-network
    restart: unless-stopped

networks:
  tecnoguard-network:
    driver: bridge