CREATE TABLE tb_workorders
(
    id                  BIGSERIAL PRIMARY KEY,
    description         TEXT        NOT NULL,
    equipment           VARCHAR(255),
    client              VARCHAR(255),
    workorder_status    VARCHAR(20) NOT NULL,
    workorder_type      VARCHAR(20) NOT NULL,
    estimated_hours     DECIMAL(10, 2),
    actual_hours        DECIMAL(10, 2),
    estimated_cost      DECIMAL(10, 2),
    actual_cost         DECIMAL(10, 2),
    assigned_technician VARCHAR(255),
    workorder_priority  VARCHAR(10) NOT NULL,
    requires_shutdown   BOOLEAN              DEFAULT FALSE,
    safety_risk         BOOLEAN              DEFAULT FALSE,
    maintenance_trigger VARCHAR(20),
    scheduled_date      DATE,
    opening_date        TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    start_date          TIMESTAMP WITHOUT TIME ZONE,
    closing_date        TIMESTAMP WITHOUT TIME ZONE,
    cancel_date         TIMESTAMP WITHOUT TIME ZONE,
    cancel_reason       TEXT,
    active              BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by          TEXT        NOT NULL,
    updated_at          TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_by          TEXT
);