CREATE TABLE tb_workorder (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    description TEXT NOT NULL,
    equipment VARCHAR(255),
    client VARCHAR(255),
    status VARCHAR(20) NOT NULL,
    workorder_type VARCHAR(20) NOT NULL,
    estimated_hours NUMERIC(10,2),
    actual_hours NUMERIC(10,2),
    estimated_cost NUMERIC(10, 2),
    actual_cost NUMERIC(10, 2),
    assigned_technician VARCHAR(255),
    workorder_priority VARCHAR(10) NOT NULL,
    requires_shutdown BOOLEAN,
    safety_risk BOOLEAN,
    maintenance_trigger VARCHAR(20),
    scheduled_date DATE,
    opening_date TIMESTAMP,
    start_date TIMESTAMP,
    closing_date TIMESTAMP,
    cancel_date TIMESTAMP,
    cancel_reason TEXT,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL,
    created_by TEXT,
    updated_at TIMESTAMP,
    updated_by TEXT
);